// Generated by CoffeeScript 1.9.1
module.exports = function(robot) {
  var POST_MESSAGE_URL, SERVER_ADDRESS, filter_chat;
  POST_MESSAGE_URL = 'https://slack.com/api/chat.postMessage?token=<YOUR_SLACK_TOKEN>&channel=<YOUR_DEBUG_CHANNEL>&username=<YOUR_SLACK_USERNAME>&as_user=true&pretty=1&&text=';
  SERVER_ADDRESS = "[COMPUTATIONAL_SERVER_ADDRESS]:5000";
  robot.respond(/set production/i, function(res) {
    robot.brain.set('production', 1);
    res.reply('Set production = ' + robot.brain.get('production'));
  });
  robot.respond(/set no production/i, function(res) {
    robot.brain.set('production', 0);
    res.reply('Set production = ' + robot.brain.get('production'));
  });
  robot.respond(/get production/i, function(res) {
    res.reply('Production = ' + robot.brain.get('production'));
  });
  robot.respond(/help/i, function(res) {
    var help_res;
    help_res = ['Sorry I can\'t help you. I am just a bot', 'Sorry I can\'t. Call 911 if you need emergency help.'];
    res.send(res.random(help_res));
  });
  robot.respond(/you talked, finally/i, function(res) {
    res.send('Yea right, I am quite a slow learner, but better late than never!');
  });
  robot.respond(/what can you do/i, function(res) {
    res.send('I do nothing.');
    res.send('I just listen to you guys and speak a sentence or two when I feel like to.');
    res.send('Keep talking, the more you talk, the more intelligent I will be.');
  });
  filter_chat = function(s) {
    return s.match(/set production/i) || s.match(/set no production/i) || s.match(/get production/i) || s.match(/help/i) || s.match(/you talked, finally/i) || s.match(/what can you do/i);
  };
  return robot.hear(/(.*)/i, function(res) {
    var SERVER_URL, s;
    s = res.match[0];
    if (filter_chat(s)) {
      return;
    }
    if (robot.brain.get('production') > 0) {
      SERVER_URL = SERVER_ADDRESS + "/chat?input=";
      return robot.http(SERVER_URL + res.match[0]).get()(function(err, res1, body1) {
        if ((body1 !== "") && (body1 !== "UNK")) {
          return res.send(body1);
        }
      });
    } else {
      SERVER_URL = SERVER_ADDRESS + "/chat?debug=yes&input=";
      return robot.http(SERVER_URL + res.match[0]).get()(function(err2, res2, body2) {
        if (body2 !== "") {
          return robot.http(POST_MESSAGE_URL + "Answer for: " + s + "\n" + body2).get()(function(err3, res3, body3) {});
        }
      });
    }
  });
};
